name: Zubo Daily SpeedTest
on:
  schedule:
    - cron: '0 20 * * *' # 每天凌晨 4 点运行 (UTC时间+8)
  workflow_dispatch:      # 允许手动在页面点击运行

permissions:
  contents: write         # 必须有这个权限才能 push 文件

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install httpx

      - name: Run SpeedTest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # 运行刚才写的脚本
        run: python py/zubo_speedtest.py

      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add zubo_live.txt
          # 如果没有变化则不提交
          git commit -m "Auto Update Speedtested List" || exit 0
          git push
